title: SCP
url: ""
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#111f5a"
  secondary-color: "#4372d6"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#372789"
    - title: media-color-three
      color: "#00088f"
    - title: media-color-four
      color: "#6169ad"
    - title: media-color-five
      color: "#5a6d8b"
resources_name: Resources
description: Display something
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://mfa-scp-staging.netlify.app
prod: https://mfa-scp-prod.netlify.app
is_government: true
shareicon: /images/scplogo.png
